[versions]
library = "1.1.0"
android = "8.1.4"
android-core = "1.12.0"
appdirs = "1.2.2"
compose = "1.6.0-alpha01"
coroutines = "1.8.0-RC2"
decompose = "3.0.0-alpha04"
dokka = "1.9.10"
kotlin = "1.9.22"
lang = "3.14.0"
publish = "0.25.3"

[libraries]
android = { group = "androidx.core", name = "core-ktx", version.ref = "android-core" }
appdirs = { group = "net.harawata", name = "appdirs", version.ref = "appdirs" }
coroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }
coroutines-swing = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-swing", version.ref = "coroutines" }
decompose = { group = "com.arkivanov.decompose", name = "decompose", version.ref = "decompose" }
decompose-compose = { group = "com.arkivanov.decompose", name = "extensions-compose", version.ref = "decompose" }
lang = { group = "org.apache.commons", name = "commons-lang3", version.ref = "lang" }

[plugins]
android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
android-application = { id = "com.android.application", version.ref = "android" }
android-library = { id = "com.android.library", version.ref = "android" }
compose = { id = "org.jetbrains.compose", version.ref = "compose" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
publish = { id = "com.vanniktech.maven.publish", version.ref = "publish" }